[build]
builder = "DOCKERFILE"

[deploy]
releaseCommand = "python manage.py migrate --no-input"
healthcheckPath = "/up"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
