[build]
builder = "DOCKERFILE"

[deploy]
releaseCommand = "python manage.py migrate --no-input"
startCommand = "gunicorn finances_api.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
healthcheckPath = "/up"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
