# Generated by Django 5.0.6 on 2026-05-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('BOB', 'Boliviano'), ('USD', 'US Dollar')], default='BOB', max_length=3),
        ),
    ]
