# Generated by Django 5.0.6 on 2026-06-17 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_create_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('transferred_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transfers_in', to='api.account')),
                ('origin_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transfers_out', to='api.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transfers',
            },
        ),
    ]
