# Generated by Django 5.0.6 on 2026-06-17 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_transfer_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='spending',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer', to='api.spending'),
        ),
    ]
