# Generated by Django 5.0.6 on 2026-06-17 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transfer_add_spending_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='spending',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer', to='api.spending'),
        ),
    ]
